name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@alapatbh'
      # - run: npm install
      - run: npm config set //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
      - name: Publish to GitHub Packages
      - run: |
          npm publish SNS-SQS-FOLDER
          npm publish SECOND-FOLDER
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}